version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
        - POSTGRES_PASSWORD=ml_ops
        - POSTGRES_USER=ml_ops
        - POSTGRES_DB=ml_ops_db
    ports:
      - '5433:5432'
    command: -c fsync=off -c full_page_writes=off
    tmpfs: /var/lib/postgresql/data


